name: archiq-ai-backend
services:
  - type: web
    name: archiq-ai-api
    runtime: docker
    repo: https://github.com/K09-0/ARCHIQ-AI
    branch: main
    rootDir: backend
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: HF_OCR_MODEL
        value: microsoft/trocr-base-printed
      - key: DB_PATH
        value: /data/norms.db
    disk:
      name: archiq-data
      mountPath: /data
      sizeGB: 1
